# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleset',
            name='candidatealphabet',
            field=models.CharField(default='0123456789', help_text='The alphabet vector that is attempted in this particular sample set.When performing a divide and conquer attack, this will typically be a subset of the knownnextalphabet. In an iterative attack, it will be a single symbol of knownnextalphabet.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleset',
            name='data',
            field=models.TextField(default='', help_text='The raw data collected on the network for this sampleset'),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='knownalphabet',
            field=models.CharField(default='0123456789', help_text='The candidate alphabet for the next unknown character', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='completed',
            field=models.DateTimeField(blank=True, help_text='When we stopped collecting samples for this sampleset, successfully or not', null=True),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='knownsecret',
            field=models.CharField(default='', help_text='Known secret before the sample set was collected', max_length=255),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='success',
            field=models.BooleanField(default=False, help_text='Whether the samples in this sampleset were all collected successfully'),
        ),
    ]
