# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0002_auto_20160303_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='maxreflectionlength',
            field=models.IntegerField(default=0, help_text='The maximum length that will be reflected by the service the designated location within the endpoint. If this is 0 then there is no limit in the reflection length.'),
        ),
    ]
