# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0003_target_maxreflectionlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='snifferendpoint',
            field=models.CharField(default='', help_text="The HTTP endpoint of the adversarial sniffer running on the victim's network which is listening for our HTTP requests. This endpoint must include the 'http://' prefix.", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victim',
            name='sourceip',
            field=models.GenericIPAddressField(default='192.168.1.2', help_text='Source IP on the local network, e.g. 192.168.10.140'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='alphabet',
            field=models.CharField(help_text=('This set contains all the candidate symbols each ', 'character of the secret can be.'), max_length=255),
        ),
        migrations.AlterField(
            model_name='target',
            name='endpoint',
            field=models.CharField(help_text="The endpoint in full URL form, including 'https://'.The endpoint string must contain a '%s' to mark the position in which the string-to-be-reflected will be replaced into.", max_length=255),
        ),
        migrations.AlterField(
            model_name='target',
            name='prefix',
            field=models.CharField(help_text='The known prefix of the secret used to bootstrap the attack.', max_length=255),
        ),
    ]
