# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0004_auto_20160305_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleset',
            name='round',
            field=models.IntegerField(default=1, help_text='Which round this sampleset belongs to. Each round contains the collection of multiple samplesets pertaining to different candidate alphabets. To complete a round, enough samplesets must be completed to be able to make a decision for a state transition with a certain confidence.'),
        ),
        migrations.AddField(
            model_name='victim',
            name='round',
            field=models.IntegerField(default=1, help_text='Which round the attack is currently running on. This starts at 1 and advances by 1 in each round until the attack is concluded. The latest samplesets collected for the victim always pertain to the current round.'),
        ),
    ]
