# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0005_auto_20160305_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleset',
            name='roundcardinality',
            field=models.IntegerField(default=1, help_text="How many alphabet symbols are being tested in this round.This can be larger or equal to the current sampleset's candidatealphabet length, as other samplesets may not have the same candidatealphabet length. This discrepancy occurs when the target alphabet is not a perfect power of 2."),
        ),
    ]
