# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0007_auto_20160309_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='amount',
            field=models.IntegerField(default=1, help_text='Number of samples contained in each sampleset of this round.'),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='completed',
            field=models.DateTimeField(blank=True, default=None, help_text='When we stopped collecting samples for this sampleset, successfully or not', null=True),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='started',
            field=models.DateTimeField(blank=True, default=None, help_text='Date and time at which sample set collection was started', null=True),
        ),
    ]
