# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0008_auto_20160314_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='method',
            field=models.CharField(default='divide&conquer', help_text='Method of building candidate samplesets.', max_length=255),
        ),
    ]
