# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0009_victim_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='roundcardinality',
        ),
        migrations.AddField(
            model_name='round',
            name='maxroundcardinality',
            field=models.IntegerField(default=1, help_text="The maximum amount of symbols that will be tested in this round by a single sampleset. This can be larger or equal to the current sampleset's candidatealphabet length, as other samplesets may not have the same candidatealphabet length. This discrepancy occurs when the target alphabet is not a perfect power of 2."),
        ),
        migrations.AddField(
            model_name='round',
            name='minroundcardinality',
            field=models.IntegerField(default=1, help_text="The minimum amount of symbols that will be tested in this round by a single sampleset. This can be less or equal to the current sampleset's candidatealphabet length."),
        ),
    ]
