# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0010_auto_20160318_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleset',
            name='alignmentalphabet',
            field=models.CharField(default='', help_text='The alphabet used for padding in order to achieve block alignment for this batch. This is a permutation of the target alignment alphabet.', max_length=255),
        ),
        migrations.AddField(
            model_name='target',
            name='alignmentalphabet',
            field=models.CharField(default='', help_text='Alphabet used for block alignment. This will be shuffled once per batch.', max_length=255),
        ),
    ]
