# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0011_auto_20160325_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='recordscardinality',
            field=models.IntegerField(default=0, help_text='The amount of expected TLS response records per request. If 0 then the amount is not known or is expected to change per request.'),
        ),
    ]
