# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0012_target_recordscardinality'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='port',
            field=models.IntegerField(default=443, help_text='The port that responses are expected to come from. For TLS this should generally be 443.'),
        ),
        migrations.AddField(
            model_name='victim',
            name='interface',
            field=models.CharField(default='wlan0', help_text="Attacking machine's interface that is on the victim's network.", max_length=255),
        ),
    ]
