# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0013_auto_20160330_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='method',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=2, help_text='Method of building candidate samplesets.'),
        ),
    ]
