# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0015_auto_20160511_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='method',
        ),
        migrations.AddField(
            model_name='target',
            name='method',
            field=models.IntegerField(choices=[(1, 'serial'), (2, 'divide&conquer')], default=1, help_text='Method of building candidate samplesets.'),
        ),
        migrations.AddField(
            model_name='target',
            name='name',
            field=models.CharField(default='', help_text='A unique name identifying the target.', max_length=255, unique=True),
        ),
    ]
