# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0016_auto_20160514_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='block_align',
            field=models.BooleanField(default=True, help_text='Whether to use block alignment or not, in case maxreflectionlength does not allow it'),
        ),
        migrations.AddField(
            model_name='target',
            name='huffman_pool',
            field=models.BooleanField(default=True, help_text='Whether to use Huffman pool or not, in case maxreflectionlength does not allow it'),
        ),
    ]
