# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0017_auto_20160530_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='samplesize',
            field=models.IntegerField(default=64, help_text='The amount of samples per sampleset.'),
        ),
    ]
