# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0020_target_sentinel'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='alignmentsize',
            field=models.IntegerField(default=16, help_text='The size of the used alignment alphabet. This should be equal to the block size in bytes.'),
        ),
    ]
