# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0021_auto_20161025_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='trashed_at',
            field=models.DateTimeField(blank=True, help_text='The datatime of the first delete request.On a second delete request, the victim isdeleted. It iss used for undoing deletion.', null=True),
        ),
    ]
