# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-03 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0021_update_victim_target_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='trashed_at',
            field=models.DateTimeField(blank=True, help_text='The datatime of the delete request.', null=True),
        ),
    ]
