# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-31 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0022_auto_20170203_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='accumulated_probability',
            field=models.FloatField(default=1.0, help_text="Accumulated probability of current round's given knownsecret. "),
        ),
        migrations.AddField(
            model_name='round',
            name='completed',
            field=models.DateTimeField(blank=True, default=None, help_text='When we stopped round, successfully or not', null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='started',
            field=models.DateTimeField(blank=True, default=None, help_text='Date and time since round was started', null=True),
        ),
    ]
