# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0023_auto_20170513_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='accumulated_probability',
            field=models.FloatField(default=1.0, help_text="Accumulated probability of current round's given knownsecret. "),
        ),
    ]
