# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-01 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0023_auto_20170531_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='method',
            field=models.IntegerField(choices=[(1, 'serial'), (2, 'divide&conquer'), (3, 'backtracking')], default=1, help_text='Method of building candidate samplesets.'),
        ),
    ]
