# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0025_auto_20171130_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='amplification_factor',
            field=models.FloatField(default=1.05, help_text='The amplification factor that is used for the the backtracking execution.'),
        ),
        migrations.AddField(
            model_name='target',
            name='compression_function_factor',
            field=models.FloatField(default=1.05, help_text='The compression factor that is used for the the backtracking execution.'),
        ),
    ]
