# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0026_auto_20171208_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='block_align',
            field=models.BooleanField(default=True, help_text='Whether to use block alignment or not, in case maxreflectionlength does not allow it'),
        ),
        migrations.AddField(
            model_name='round',
            name='huffman_pool',
            field=models.BooleanField(default=True, help_text='Whether to use Huffman pool or not, in case maxreflectionlength does not allow it'),
        ),
        migrations.AddField(
            model_name='round',
            name='method',
            field=models.IntegerField(choices=[(1, 'serial'), (2, 'divide&conquer'), (3, 'backtracking')], default=1, help_text='Method of building candidate samplesets.'),
        ),
    ]
