# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0027_auto_20171210_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='huffman_balance',
            field=models.BooleanField(default=True, help_text='Whether to use huffman balance for match symbols.'),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='huffman_match_balance',
            field=models.CharField(default='', help_text='The alphabet used for balancing the Huffman tree for the match pointers.', max_length=255),
        ),
        migrations.AddField(
            model_name='target',
            name='huffman_balance',
            field=models.BooleanField(default=True, help_text='Whether to use huffman balance for match symbols.'),
        ),
    ]
